spring:
  profiles:
    active: development
    group:
      development:
        - base
        - development-env
      docker:
        - base
        - development-env
        - docker-env
      production:
        - base
        - production-env